#!/usr/bin/env ansible-playbook

---

- name: Setup the ansible control host for use with this repo
  hosts: localhost
  tasks:

    - name: create required directories
      file:
        path: "~/.ansible/{{ item }}"
        serole: undefined
        state: directory
      loop:
        - "logs"
        - "retry"

    - name: Install python dependencies
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"

    - name: Install ansible role dependencies
      shell: "ansible-galaxy install -r {{ playbook_dir }}/roles/requirements.yaml -p {{ playbook_dir }}/roles --force"