---
argument_spec:
  ansible_network_os:
    description:
      - Set the name of the Ansible network OS platform.  This value should be
        set to `junos` for this provider.
    required: true

  junos_config_text:
    description:
      - Provide the network device configuration as a single string.  The
        configuration text will be loaded onto the target network deivce.
    type: str
    required: True

  junos_config_replace:
    description:
      - This value enables or disables the configuration replace feature of the function.
    type: bool
    default: False

  junos_config_remove_temp_files:
    description:
      - Configures the function to remove or not remove the temp files created when preparing
        to load the configuration file. There are two locations for temp files, one on the
        Ansible controller and one on the device. This argument accepts a boolean value.
    type: bool
    default: True
